#!/usr/bin/env python

import urllib2, sys

url = sys.argv[1]

file_name = url.split('/')[-1]
u = urllib2.urlopen(url)
f = open(file_name, 'wb')
meta = u.info()
file_size = int(meta.getheaders("Content-Length")[0])
print "Downloading: %s Bytes: %s" % (file_name, file_size)

file_size_dl = 0
block_sz = 8192

while True:
    buf = u.read(block_sz)
    if not buf:
        break

    file_size_dl += len(buf)
    f.write(buf)
    percentage = file_size_dl * 100. / file_size
    status = r"%10d  [%3.2f%%]" % (file_size_dl, percentage)
    status = status + chr(8)*(len(status)+1)
    print status,

f.close()
